-- Create database and table
CREATE DATABASE IF NOT EXISTS city_issues;
USE city_issues;

CREATE TABLE IF NOT EXISTS issues (
    id INT AUTO_INCREMENT PRIMARY KEY,
    description TEXT
);

-- Insert sample data
INSERT INTO issues (description) VALUES
("My house lost electricity last night."),
("Water stopped coming through the taps."),
("There was a blackout in my neighborhood."),
("Street lights are not working."),
("The garbage hasn’t been collected."),
("Power line down across the street.");

-- Add 100 more random issue descriptions
INSERT INTO issues (description) VALUES
("There's a strange smell coming from the sewer."),
("My apartment heating is not working."),
("Pothole on the main road near my house."),
("Public fountain is overflowing."),
("Wi-Fi has been unstable since yesterday."),
("Garbage trucks missed our street again."),
("The park lights aren't turning on at night."),
("Street flooded after a light rain."),
("Broken traffic light at the intersection."),
("Noise complaint from nearby construction."),
("Tree fell during the windstorm."),
("My mailbox was vandalized."),
("Someone dumped a couch in the alley."),
("There are stray dogs near the school."),
("Recycling bins are overflowing."),
("Sidewalk is cracked and unsafe."),
("The elevator in our building is stuck."),
("Public restrooms at the park are locked."),
("Water leak in community center."),
("Loud music from a neighbor every night."),
("Overgrown weeds on public property."),
("Power surge damaged my appliances."),
("The bus stop shelter was shattered."),
("Heavy vibration from nearby trucks."),
("Graffiti all over the playground."),
("Lamp posts are constantly flickering."),
("Storm drain is completely clogged."),
("The train crossing signal malfunctions."),
("The crosswalk button doesn't work."),
("A raccoon keeps getting into trash bins."),
("The community pool smells odd."),
("Fence broken in the public garden."),
("Side street has no signage."),
("Fire hydrant is leaking."),
("City app not responding to reports."),
("Air smells of burning plastic."),
("Toxic foam in the creek."),
("Broken benches in town square."),
("Creepy man loitering near the library."),
("Public bike racks are damaged."),
("Children's slide has sharp edges."),
("Street is always wet with no rain."),
("Lost dog wandering the area."),
("Illegal dumping behind the supermarket."),
("Power keeps going out every evening."),
("Huge pothole on highway off-ramp."),
("Construction crew working past legal hours."),
("Noise from bar past midnight."),
("Stray cat colony growing out of control."),
("Public notice signs torn down."),
("People smoking near hospital entrance."),
("Dumpster smells really bad."),
("Public art sculpture has been defaced."),
("Parking meters aren't accepting cards."),
("Manhole cover is loose."),
("The public bus is constantly late."),
("No street name on the new development."),
("Mosquito infestation near pond."),
("People racing on residential streets."),
("City worker abandoned equipment."),
("Playground swings have chains missing."),
("The ATM near city hall was tampered with."),
("Community newsletter hasn't been delivered."),
("Overflowing trash can at the beach."),
("Flickering LED screen downtown."),
("Sidewalk is blocked by parked cars."),
("Storm blew off roof tiles on bus station."),
("Library AC not working."),
("Rotten smell from compost drop-off."),
("I saw rats near the food court."),
("The canal water is strangely colored."),
("Shuttle bus skipped my stop."),
("Fire alarm keeps going off falsely."),
("Public fountain smells bad."),
("Sidewalk flooded due to sprinkler system."),
("Police sirens all night."),
("Stagnant water is attracting bugs."),
("Man playing loud drums downtown."),
("No water in public restroom."),
("Park gates don’t close properly."),
("Crack in the foundation of civic hall."),
("City web portal shows wrong information."),
("People using drones in no-fly zone."),
("Municipal sign is upside down."),
("Public benches occupied by people sleeping."),
("Outlet in public charging station sparks."),
("The CCTV camera is dangling."),
("Large crack in skate park ramp."),
("Traffic cones left in middle of road."),
("Someone keyed my car outside city office."),
("Broken window at community center."),
("Flooding at underpass during rain."),
("Leaky pipe outside library."),
("Dumpster fire last night."),
("No streetlights on Pine Avenue."),
("Trash collector skipped our block."),
("Old mattress dumped in front yard."),
("Metal rod sticking out of sidewalk."),
("Fire hydrant is blocked by car."),
("Unusual power fluctuations all week."),
("Gate at community dog park is jammed."),
("Lack of accessibility ramps downtown."),
("Public phone booth is vandalized."),
("Open electrical box on street corner.");
